config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/eosc-perf:
      branch: master
      repo: https://github.com/EOSC-synergy/eosc-perf
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/eosc-perf git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-chestnut-ragdoll.sh
        container: qc.acc_muzzy-platinum-cattle
  QC.Doc:
    repos:
      github.com/EOSC-synergy/eosc-perf find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-corn-lemming.sh
        container: qc.doc_surly-wisteria-gibbon
      github.com/EOSC-synergy/eosc-perf git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-lilac-burmese.sh
        container: qc.doc_randy-cobalt-collie
      github.com/EOSC-synergy/eosc-perf markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-rose-mandrill.sh
        container: qc.doc_smelly-thistle-barb
      github.com/EOSC-synergy/eosc-perf restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-chocolate-affenpinscher.sh
        container: qc.doc_goopy-red-lemming
  QC.Lic:
    repos:
      github.com/EOSC-synergy/eosc-perf licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-sangria-snake.sh
        container: qc.lic_whiny-asparagus-lionfish
  QC.Sec:
    repos:
      github.com/EOSC-synergy/eosc-perf bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-cyan-loon.sh
        container: qc.sec_homely-salmon-gorilla
  QC.Sty:
    repos:
      github.com/EOSC-synergy/eosc-perf flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-sepia-weasel.sh
        container: qc.sty_hilly-blue-dodo
      github.com/EOSC-synergy/eosc-perf hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-seashell-bloodhound.sh
        container: qc.sty_gummy-puce-flounder
      github.com/EOSC-synergy/eosc-perf jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-turquoise-abyssinian.sh
        container: qc.sty_muzzy-cinnamon-scorpion
  QC.Ver:
    repos:
      github.com/EOSC-synergy/eosc-perf get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-violet-chamois.sh
        container: qc.ver_trippy-carmine-cuttlefish
timeout: 5400
